name: Spec Run Tasks (GLM optional)

on:
  workflow_dispatch:
    inputs:
      spec_id:
        description: "Spec ID"
        required: true
      slug:
        description: "Slug"
        required: true
      repo:
        description: "Target repo (e.g., lablab-bean)"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run task suggestions (no write)
        env:
          GLM_API_KEY: ${{ secrets.GLM_API_KEY }}
          GLM_BASE_URL: ${{ secrets.GLM_BASE_URL }}
          GLM_MODEL: ${{ vars.GLM_MODEL }}
          LABLAB_SPECS_BASE: /srv/specs
        run: |
          python -m agents.langgraph.run_tasks --spec "${{ inputs.spec_id }}" --slug "${{ inputs.slug }}" --repo "${{ inputs.repo }}"
